apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-easy-notes-app
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: node-easy-notes-app  
    spec:     # pod spec                  
      containers: 
      - name: node-easy-notes-app 
        image: gcr.io/tnplmicro/node-easy-notes-app:v1 # image we pushed
        ports:
        - containerPort: 3000
